# This file was generated by the {rix} R package v0.17.2 on 2026-02-04
# with following call:
# >rix(date = "2026-02-02",
#  > r_pkgs = c("tidyverse",
#  > "ggplot2",
#  > "scales",
#  > "forcats",
#  > "svglite",
#  > "viridis",
#  > "gtExtras",
#  > "gridExtra",
#  > "DiagrammeR",
#  > "DiagrammeRsvg",
#  > "rsvg",
#  > "reticulate",
#  > "rmarkdown",
#  > "quarto"),
#  > system_pkgs = c("quarto",
#  > "git",
#  > "cacert"),
#  > py_conf = list(py_version = "3.13",
#  > py_pkgs = c("polars",
#  > "great-tables")),
#  > ide = "none",
#  > project_path = ".",
#  > overwrite = TRUE,
#  > print = TRUE,
#  > shell_hook = "export SSL_CERT_FILE=${cacert}/etc/ssl/certs/ca-bundle.crt",
#  > r_ver = "4.5.2")
# It uses the `rstats-on-nix` fork of `nixpkgs` which provides improved
# compatibility with older R versions and R packages for Linux/WSL and
# Apple Silicon computers.
# Report any issues to https://github.com/ropensci/rix
let
 pkgs = import (fetchTarball "https://github.com/rstats-on-nix/nixpkgs/archive/2026-02-02.tar.gz") {};
 
  rpkgs = builtins.attrValues {
    inherit (pkgs.rPackages) 
      DiagrammeR
      DiagrammeRsvg
      forcats
      ggplot2
      gridExtra
      gtExtras
      quarto
      reticulate
      rmarkdown
      rsvg
      scales
      svglite
      tidyverse
      viridis;
  };
   
  pyconf = builtins.attrValues {
    inherit (pkgs.python313Packages) 
      pip
      ipykernel
      great-tables
      polars;
  };
   
  system_packages = builtins.attrValues {
    inherit (pkgs) 
      R
      cacert
      git
      glibcLocales
      nix
      python313
      quarto
      which
      pandoc;
  };
  
    shell = pkgs.mkShell {
    LOCALE_ARCHIVE = if pkgs.system == "x86_64-linux" then "${pkgs.glibcLocales}/lib/locale/locale-archive" else "";
    LANG = "en_US.UTF-8";
    LC_ALL = "en_US.UTF-8";
    LC_TIME = "en_US.UTF-8";
    LC_MONETARY = "en_US.UTF-8";
    LC_PAPER = "en_US.UTF-8";
    LC_MEASUREMENT = "en_US.UTF-8";
    RETICULATE_PYTHON = "${pkgs.python313}/bin/python";
    SSL_CERT_FILE = "${pkgs.cacert}/etc/ssl/certs/ca-bundle.crt";
    NIX_SSL_CERT_FILE = "${pkgs.cacert}/etc/ssl/certs/ca-bundle.crt";
    __noChroot = true;
    buildInputs = [ rpkgs pyconf system_packages ];
  };
in
  {
    inherit pkgs shell;
  }
